name: testui
description: Test UI

version: 1.1.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: ""
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
